# Starter pipeline

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: NexPloitScan@3
  inputs:
    apiToken: 'nbr50cv.nexa.avwdtsno7theo0c2houmqmnecta1om0b'
    hostname: 'nexploit.app'
    module: 'dast'
    discoveryTypes: 'crawler'
    crawlerUrls: 'https://brokencrystals.com'
    scanTests: 'angular_csti,jwt,date_manipulation,cookie_security,csrf,directory_listing,dom_xss,file_upload,full_path_disclosure,header_security,http_method_fuzzing,secret_tokens,version_control_systems,wordpress'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
