trigger:
- repeater

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: |
    npm install
    npm install @brightsec/cli -g || true
      echo "Start Repeater 🏁"
      PID_REPEATER=$(bright-cli repeater --token {BRIGHT_TOKEN} --id {REPEATER_ID} &> /dev/null & echo $!)
      echo "Repeater started PID: $PID_REPEATER"
      sleep 10
      echo "Start BRIGHT Scan 🏁"
      SCAN_ID=$(bright-cli scan:run --token {BRIGHT_TOKEN} --repeater {REPEATER_ID} --name "Azure scan with repeater" --crawler https://brokencrystals.com/ --smart)
      echo "Scan was started with ID https://app.brightsec.com/scans/$SCAN_ID\n"
      sleep 10
      echo "Wait for issues ⏳"
      RESULT=$(bright-cli scan:polling --interval 30s --timeout 20m --token {BRIGHT_TOKEN} --breakpoint medium_issue $SCAN_ID)
      if [ -z "$RESULT" ]
      then
          echo "Failed to stop scan"
      else
          echo "Stop Scan 🛑"
          bright-cli scan:stop --token {BRIGHT_TOKEN} $SCAN_ID
      fi