trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NexPloitScan@3
  inputs:
    hostname: 'nexploit.app'
    module: 'dast'
    discoveryTypes: 'crawler'
    crawlerUrls: 'https://brokencrystals.com'
    scanTests: 'jwt'
